<?php

namespace Proxies\__CG__\MTD\TurismoBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Usuario extends \MTD\TurismoBundle\Entity\Usuario implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'MTD\\TurismoBundle\\Entity\\Usuario' . "\0" . 'id', '' . "\0" . 'MTD\\TurismoBundle\\Entity\\Usuario' . "\0" . 'nombre', '' . "\0" . 'MTD\\TurismoBundle\\Entity\\Usuario' . "\0" . 'apellido', '' . "\0" . 'MTD\\TurismoBundle\\Entity\\Usuario' . "\0" . 'edad', '' . "\0" . 'MTD\\TurismoBundle\\Entity\\Usuario' . "\0" . 'telefono', '' . "\0" . 'MTD\\TurismoBundle\\Entity\\Usuario' . "\0" . 'ci', '' . "\0" . 'MTD\\TurismoBundle\\Entity\\Usuario' . "\0" . 'contrasena', '' . "\0" . 'MTD\\TurismoBundle\\Entity\\Usuario' . "\0" . 'activo', '' . "\0" . 'MTD\\TurismoBundle\\Entity\\Usuario' . "\0" . 'paquete', '' . "\0" . 'MTD\\TurismoBundle\\Entity\\Usuario' . "\0" . 'tipo');
        }

        return array('__isInitialized__', '' . "\0" . 'MTD\\TurismoBundle\\Entity\\Usuario' . "\0" . 'id', '' . "\0" . 'MTD\\TurismoBundle\\Entity\\Usuario' . "\0" . 'nombre', '' . "\0" . 'MTD\\TurismoBundle\\Entity\\Usuario' . "\0" . 'apellido', '' . "\0" . 'MTD\\TurismoBundle\\Entity\\Usuario' . "\0" . 'edad', '' . "\0" . 'MTD\\TurismoBundle\\Entity\\Usuario' . "\0" . 'telefono', '' . "\0" . 'MTD\\TurismoBundle\\Entity\\Usuario' . "\0" . 'ci', '' . "\0" . 'MTD\\TurismoBundle\\Entity\\Usuario' . "\0" . 'contrasena', '' . "\0" . 'MTD\\TurismoBundle\\Entity\\Usuario' . "\0" . 'activo', '' . "\0" . 'MTD\\TurismoBundle\\Entity\\Usuario' . "\0" . 'paquete', '' . "\0" . 'MTD\\TurismoBundle\\Entity\\Usuario' . "\0" . 'tipo');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Usuario $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function addPaquete(\MTD\TurismoBundle\Entity\Paquete $paquete)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPaquete', array($paquete));

        return parent::addPaquete($paquete);
    }

    /**
     * {@inheritDoc}
     */
    public function removePaquete(\MTD\TurismoBundle\Entity\Paquete $paquete)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePaquete', array($paquete));

        return parent::removePaquete($paquete);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaquete()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaquete', array());

        return parent::getPaquete();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipo(\MTD\TurismoBundle\Entity\Tipo $tipo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipo', array($tipo));

        return parent::setTipo($tipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipo', array());

        return parent::getTipo();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', array($nombre));

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', array());

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setApellido($apellido)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApellido', array($apellido));

        return parent::setApellido($apellido);
    }

    /**
     * {@inheritDoc}
     */
    public function getApellido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApellido', array());

        return parent::getApellido();
    }

    /**
     * {@inheritDoc}
     */
    public function setEdad($edad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEdad', array($edad));

        return parent::setEdad($edad);
    }

    /**
     * {@inheritDoc}
     */
    public function getEdad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEdad', array());

        return parent::getEdad();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefono($telefono)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefono', array($telefono));

        return parent::setTelefono($telefono);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono', array());

        return parent::getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    public function setCi($ci)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCi', array($ci));

        return parent::setCi($ci);
    }

    /**
     * {@inheritDoc}
     */
    public function getCi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCi', array());

        return parent::getCi();
    }

    /**
     * {@inheritDoc}
     */
    public function setContrasena($contrasena)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContrasena', array($contrasena));

        return parent::setContrasena($contrasena);
    }

    /**
     * {@inheritDoc}
     */
    public function getContrasena()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContrasena', array());

        return parent::getContrasena();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivo($activo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivo', array($activo));

        return parent::setActivo($activo);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivo', array());

        return parent::getActivo();
    }

}
